### ISSUE TITLE
期望

### ISSUE THREAD

**Issue by minchieh-fay** [misakamikodo/mhxy_script#10]
感谢楼主提供的免费代码, 找时间研究一下

我有个期望, 斗胆提一下:  这个游戏, 晚间活动, 副本, 地煞活动什么的我们都愿意自己打(5开打, 很快)
特别是副本  我们大号追求低回合过   这样奖励更好
让我最烦的是部分日常活动, 最烦的是宝图, 要点10次, 时间最久的是秘境(30分钟)

我如果作为玩家, 我的实际需求是:  
能自动切到第二套装备(环装), 自动完成以下任务
宝图+师门+秘境+答题  非常希望有个工具做掉

实际场景:
一个n100的小盒子(windows)连着一个4G的热点 (每刷玩6个号, python调用adb让手机切一次飞行模式->更换IP)
白天启动开始刷: 宝图+师门+秘境,   然后做临时符摆摊8张,  挂离线抓鬼(换下一个角色)
晚上17点后,  切所有角色答题+领日常1000金币 -> 再次摆摊8张临时符  -> 离线抓鬼 -> 换角色

**Comment by minchieh-fay** [comment]
你做的功能太多了
我觉得核心只要完成 自动关闭弹窗+家园休息+ 刮刮乐+帮派签到+宝图+师门+秘境 + 答题 + 离线抓鬼就可以了
100活力肯定满~~~

如果能自动用adb切ip  就更完美了

晚间活动这种可以不要做的

**Comment by minchieh-fay** [comment]
可以尝试再众创的N100小主机上安装
这样你也不用纠结opencv打包不进去的问题了
你直接出硬件  绑定硬盘号   程序绑定硬盘号+在线升级

你700买盒子, 1000卖给我们, 也可以大批量卖给工作室

**Comment by misakamikodo** [comment]
小号比较多或者想搬砖挣钱直接买脱机科技就行了，据说是300一个月，按1比5金价算一天小号能赚个三万就回本了，目前看还是很稳定的，至少本区开的人都没怎么被封。用图像识别的原理注定不能做到速度和稳定性兼顾。能做的我会考虑慢慢写上去，这个仓库的更新主要还是看我本人是否需要，如果你有兴趣也懂点代码，可以在我的基础上写你需要的部分。

**Comment by minchieh-fay** [comment]
> 小号比较多或者想搬砖挣钱直接买脱机科技就行了，据说是300一个月，按1比5金价算一天小号能赚个三万就回本了，目前看还是很稳定的，至少本区开的人都没怎么被封。用图像识别的原理注定不能做到速度和稳定性兼顾。能做的我会考虑慢慢写上去，这个仓库的更新主要还是看我本人是否需要，如果你有兴趣也懂点代码，可以在我的基础上写你需要的部分。

你说的对, 确实你个人用的软件, 我python用的不多, 找时间研究下
