### ISSUE TITLE
大佬，桌面多开有什么思路吗？

### ISSUE THREAD

**Issue by XiaoFengZizz** [misakamikodo/mhxy_script#11]
桌面5开的话

**Comment by misakamikodo** [comment]
桌面版很多人用ssk多开，我没用过，这是不合法的被发现可能给封。被封的概率应该是不高的

**Comment by XiaoFengZizz** [comment]
有啊，我用的隔离沙箱，直接复制桌面版，理论上性能够好，可以无限多开












冯金声
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月5日(周二) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [misakamikodo/mhxy_script] 大佬，桌面多开有什么思路吗？ (Issue #11)




 
桌面版很多人用ssk多开，我没用过，这是不合法的被发现可能给封。被封的概率应该是不高的

**Comment by XiaoFengZizz** [comment]
大佬，我不是说怎么多开的意思，我是说 桌面多开之后，脚本这边有啥思路吗？例如5开，同时做师门？同时挖宝图？做帮派任务？这类的

**Comment by XiaoFengZizz** [comment]
> 同个程序跑五个是可以的。我经常开两队抓鬼副本没啥问题

意思是脚本运行 5次吗？每个脚本绑定一个窗口？

**Comment by misakamikodo** [comment]
> > 同个程序跑五个是可以的。我经常开两队抓鬼副本没啥问题
> 
> 意思是脚本运行 5次吗？每个脚本绑定一个窗口？

是的

**Comment by XiaoFengZizz** [comment]
> > > 同个程序跑五个是可以的。我经常开两队抓鬼副本没啥问题
> > 
> > 
> > 意思是脚本运行 5次吗？每个脚本绑定一个窗口？
> 
> 是的

打开了新思路，感谢大佬点拨
