### ISSUE TITLE
最近测试的时候，捉鬼的时候前几轮还正常，但是会偶遇这个弹窗导致捉鬼进行不下去，大佬能帮忙点个关闭吗

### ISSUE THREAD

**Issue by zheqingjiaobula** [misakamikodo/mhxy_script#12]
![圖片](https://github.com/misakamikodo/mhxy_script/assets/43564596/77cfedf7-6038-4f88-b41d-7a8c889449d5)

**Comment by misakamikodo** [comment]
这多半是有个chasepos的配置得改改，在resources/ghost/ghost.ini的配置文件里，一般第几个任务是捉鬼就填几；
如果像你说的那样前几轮正常后面点到师门了，可能是比较老的代码，那时候过夜会把chasepos+1，后面游戏版本更新了不需要了才把这个去了

**Comment by 191443465** [comment]
> 这多半是有个chasepos的配置得改改，在resources/ghost/ghost.ini的配置文件里，一般第几个任务是捉鬼就填几； 如果像你说的那样前几轮正常后面点到师门了，可能是比较老的代码，那时候过夜会把chasepos+1，后面游戏版本更新了不需要了才把这个去了

好的，晚上試試看。多謝大佬
