### ISSUE TITLE
秒低价考古铲子可以实现吗

### ISSUE THREAD

**Issue by qq736812228** [misakamikodo/mhxy_script#15]
想用这个来秒低价考古铲子，可以实现吗 多谢大佬

**Comment by misakamikodo** [comment]
mhxy_shopping.py 是用来干这个的

**Comment by qq736812228** [comment]
大佬问一下 这个是用于模拟器里面运行的游戏，还是PC端的运行的游戏

**Comment by misakamikodo** [comment]
> 大佬问一下 这个是用于模拟器里面运行的游戏，还是PC端的运行的游戏

桌面版

**Comment by qq736812228** [comment]
大佬 现在这个程序可以用吗   我打包完之后运行exe文件，报错

**Comment by qq736812228** [comment]
![Uploading 20231224095057.png…]()

**Comment by misakamikodo** [comment]
> 大佬 现在这个程序可以用吗 我打包完之后运行exe文件，报错

不用打包用就行，正常直接用python运行文件就好了。
