### ISSUE TITLE
大佬，想问个问题，每个代码里的from mhxy import后面是把这个星号替换成下面class里的东西吗

### ISSUE THREAD

**Issue by m18267600078** [misakamikodo/mhxy_script#17]
刚学python不是很懂，替换完*之后再运行script脚本就行了是吗

**Comment by m18267600078** [comment]
大佬你是几区的，我一区再续的有没有机会带带我，目前研2闲着玩玩梦幻嘻嘻

**Comment by misakamikodo** [comment]
> 刚学python不是很懂，替换完*之后再运行script脚本就行了是吗

你想的这一步是错误的，需要做的我在ReadMe里写了
