### ISSUE TITLE
挖矿的机制

### ISSUE THREAD

**Issue by zhuqif** [misakamikodo/mhxy_script#19]
挖矿这里，运行体验后，在同一屏幕出现多个矿时，会出现遗漏的情况，这里是不是可以增加移动偏移量，重查找机制再进行识别一下

**Comment by misakamikodo** [comment]
> 挖矿这里，运行体验后，在同一屏幕出现多个矿时，会出现遗漏的情况，这里是不是可以增加移动偏移量，重查找机制再进行识别一下

是会有遗漏，我的目标就是晚上挂着把活力挖完就行，所以也没去继续优化。
