### ISSUE TITLE
这个好像用模拟器无法使用？

### ISSUE THREAD

**Issue by 1021030435** [misakamikodo/mhxy_script#2]

**Comment by misakamikodo** [comment]
桌面版的

**Comment by misakamikodo** [comment]
不能直接用，原先设置的桌面版的，要看懂代码改下参数才行。可以说代码仅供参考吧

**Comment by kanglu-bio** [comment]
请问有计划出个模拟器版本的吗？

**Comment by misakamikodo** [comment]
> 

首先把mhxy.py获取窗口相关的代码改下包括窗口名称和窗口大小这些，那部分是按窗口标题名称获取的。然后把截图替换下、写在代码里的点位坐标改改应该可以实现

**Comment by kanglu-bio** [comment]
期待大佬mumu模拟器版本

**Comment by misakamikodo** [comment]
> 期待大佬mumu模拟器版本
啊这..其实我没打算搞，我只是给你改代码提供个思路。

**Comment by kanglu-bio** [comment]
ok，有时间我来搞一下，但是感觉最麻烦的是逻辑，各种判断
