### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by kemaosen** [misakamikodo/mhxy_script#25]
pip install -r requirements.txt 创建环境出错
老哥，这个报错要怎么解决啊。ui目录下的可以正常安装。py 版本是3.11.8
![PixPin_2024-03-09_20-57-57](https://github.com/misakamikodo/mhxy_script/assets/43406263/d8476201-3713-4f65-a2e2-138044f44127)

**Comment by misakamikodo** [comment]
就是有个东西缺了，之前碰到过，按提示的装上就行了
