### ISSUE TITLE
UI层执行mhxy_tkinter.py的“一键挖矿”的问题

### ISSUE THREAD

**Issue by zhuqif** [misakamikodo/mhxy_script#26]
使用UI下的mhxy_tkinter.py执行一键挖矿时，
报错：FileNotFoundError("文件不存在")，
根据异常抛错,发现mhxy_baotu.py文件的代码：file_path = os.path.join(os.path.abspath('.'), 'resources/richang/richang.ini') 在执行时的相对路径有问题，文件执行的路径是在mhxy_script\ui下去找的resources/richang/richang.ini

我这边的解决方案是：在mhxy_script目录下创建了oschdir.py文件先定义当前执行工作目录，然后mhxy_baotu.py引用import oschdir就解决了
import os
os.chdir('G:/mhxy_script')

因为不是技术同学，只能使用这种笨方法。不知道还有哪些更好的办法呢

**Comment by misakamikodo** [comment]
用pyQt的更好，tkinter之前胡乱写的，哈哈
