### ISSUE TITLE
新版已经没有爬塔了,挖矿也没有必要弄了,有没有用过的弄个视频观摩下,我这mac跑不起来 

### ISSUE THREAD

**Issue by Unchanged-Is-Changed** [misakamikodo/mhxy_script#28]

**Comment by misakamikodo** [comment]
mac是不行的 见 [PyAutoGUI 文档](https://automatetheboringstuff.com/2e/chapter20/)里搜索”As of version 0.9.46, PyAutoGUI’s window“ 有关获取windows窗口的代码需要删除可能可以

**Comment by Unchanged-Is-Changed** [comment]
嗯.等忙过了弄台Windows笔记本试试
