### ISSUE TITLE
MUMU12模拟器 设置MD文件中的分辨率后 鼠标位置完全不对劲啊

### ISSUE THREAD

**Issue by Wz0629** [misakamikodo/mhxy_script#29]
佬 你好 
![image](https://github.com/misakamikodo/mhxy_script/assets/82069975/ed8a3fa2-8610-4db2-9ae8-62f4dbe5ee25)
他在yun运行起来的时候 完全不能按照预想的位置去执行 包括最简单的喊话功能的leftclick都不对 可以加你联系方式探讨下嘛

**Comment by misakamikodo** [comment]
一般人不应该用时空版嘛，我这是对着桌面版写的。模拟器点位肯定不一样，大部分地方都是直接写死了

**Comment by Wz0629** [comment]
是的 我看很多地方都写死了 那就是说除非和你用一样的配置 不然几乎无法使用吗
