### ISSUE TITLE
大佬能否教一下怎样运行，没时间就算了，无意冒犯

### ISSUE THREAD

**Issue by Xie-YaNing** [misakamikodo/mhxy_script#32]

**Comment by misakamikodo** [comment]
前提懂点python的话，安装好依赖后在ui包里运行pyqt那个窗口程序的python文件然后点击窗口程序的调整到小窗口。选择需要的运行，脚本的启动位置琢磨不清楚可以在资源文件夹的readme里看看，然后右下角有选择执行窗口，从左到右从上到下排序
