### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by mjie0822** [misakamikodo/mhxy_script#34]
跟踪了脚本的流程，抓鬼是存在流程上的错误的，导致无法使用

**Comment by misakamikodo** [comment]
抓鬼我用的时候还是很稳定的，可以说下哪里不对。应该在钟馗对话框或者抓鬼中的时候开始运行，然后之前可能识别对话框的代码段不是很好，后来我也没调整相当于还是用固定任务位置配置了
