### ISSUE TITLE
副本选择报错已经新增技能选择建议

### ISSUE THREAD

**Issue by j506130598** [misakamikodo/mhxy_script#36]
OSError: Failed to read resources/fuben/selectfuben.png because file is missing, has improper permissions, or is an unsupported or invalid format

看日志应该是资源文件夹下面少了选择副本的图
大佬这个能不能优化下

还有一个建议是能不能增加挂机技能选择设置（自己设置第几个技能）
应用场景在于副本打完换捉鬼的时候需要换技能（例如辅助关奶）

**Comment by misakamikodo** [comment]
缺的文件提交了

**Comment by misakamikodo** [comment]
> OSError: Failed to read resources/fuben/selectfuben.png because file is missing, has improper permissions, or is an unsupported or invalid format
> 
> 看日志应该是资源文件夹下面少了选择副本的图 大佬这个能不能优化下
> 
> 还有一个建议是能不能增加挂机技能选择设置（自己设置第几个技能） 应用场景在于副本打完换捉鬼的时候需要换技能（例如辅助关奶）

这个在捉鬼之前副本之后加个点挂机按钮切换下技能就好了，就三个点击代码自己加下喽
