### ISSUE TITLE
大佬求教下，DLL load failed while importing QtGui

### ISSUE THREAD

**Issue by asChrislai** [misakamikodo/mhxy_script#38]
Traceback (most recent call last):
  File "D:\mhxy_script-master (1)\mhxy_script-master\ui\mhxy_pyqt.py", line 5, in <module>
    from PyQt6 import QtWidgets
ImportError: DLL load failed while importing QtGui: 找不到指定的程序。

requirements依赖包显示已安装，但运行就报错

**Comment by misakamikodo** [comment]
python版本是3.8以上吗，pyQt6需要3.8的版本

**Comment by asChrislai** [comment]
python版本3.8/3.9/3.10/3.12都试过，都是报同样的异常；
一开始怀疑是环境配置问题，用ananconda也是同样的异常

**Comment by misakamikodo** [comment]
[[DLL load failed while importing QtGui](https://stackoverflow.com/questions/73893299/dll-load-failed-while-importing-qtgui)](https://stackoverflow.com/questions/73893299/dll-load-failed-while-importing-qtgui) 试试这个

**Comment by asChrislai** [comment]
按上述方案，已解决
