### ISSUE TITLE
嗨大佬，可以教一下如何使用么，是运行test.py文件嘛

### ISSUE THREAD

**Issue by haozhuoyi** [misakamikodo/mhxy_script#5]

**Comment by misakamikodo** [comment]
ReadMe.md里有写怎么能用，纯代码没窗口程序，只能按需要的跑，可能有编程基础的才能用吧。

**Comment by haozhuoyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by haozhuoyi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
