### ISSUE TITLE
请问运行mhxy.py后没有反应是什么情况呢

### ISSUE THREAD

**Issue by Yakumo-Yukari** [misakamikodo/mhxy_script#8]
![2](https://github.com/misakamikodo/mhxy_script/assets/12076232/dbc635ed-fdf0-4a8c-b969-ca69878a73ca)

大佬项目中没有提供 `requirements.txt`  吗？

我现在运行mhxy.py后没有任何反应  需要怎么做

**Comment by misakamikodo** [comment]
我觉得我写的程序想要开箱即用还是会有困难，这个程序二次开发可能更适合

**Comment by misakamikodo** [comment]
后续有空的话会研究下打个不懂代码的也能用的release包出来
